package ds.zjc.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pbis_language
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Language implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   语种名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.language_name
     *
     * @mbg.generated
     */
    private String languageName;

    /**
     * Database Column Remarks:
     *   语种缩写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.language_abbr
     *
     * @mbg.generated
     */
    private String languageAbbr;

    /**
     * Database Column Remarks:
     *   输入方式0=右对齐,1=左对齐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.input_mode
     *
     * @mbg.generated
     */
    private Byte inputMode;

    /**
     * Database Column Remarks:
     *   1代表主数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.source_system
     *
     * @mbg.generated
     */
    private Byte sourceSystem;

    /**
     * Database Column Remarks:
     *   来源系统更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.source_update_time
     *
     * @mbg.generated
     */
    private Date sourceUpdateTime;

    /**
     * Database Column Remarks:
     *   记录插入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * Database Column Remarks:
     *   记录更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_language.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbis_language
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.id
     *
     * @return the value of pbis_language.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.id
     *
     * @param id the value for pbis_language.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.language_name
     *
     * @return the value of pbis_language.language_name
     *
     * @mbg.generated
     */
    public String getLanguageName() {
        return languageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.language_name
     *
     * @param languageName the value for pbis_language.language_name
     *
     * @mbg.generated
     */
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.language_abbr
     *
     * @return the value of pbis_language.language_abbr
     *
     * @mbg.generated
     */
    public String getLanguageAbbr() {
        return languageAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.language_abbr
     *
     * @param languageAbbr the value for pbis_language.language_abbr
     *
     * @mbg.generated
     */
    public void setLanguageAbbr(String languageAbbr) {
        this.languageAbbr = languageAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.input_mode
     *
     * @return the value of pbis_language.input_mode
     *
     * @mbg.generated
     */
    public Byte getInputMode() {
        return inputMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.input_mode
     *
     * @param inputMode the value for pbis_language.input_mode
     *
     * @mbg.generated
     */
    public void setInputMode(Byte inputMode) {
        this.inputMode = inputMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.source_system
     *
     * @return the value of pbis_language.source_system
     *
     * @mbg.generated
     */
    public Byte getSourceSystem() {
        return sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.source_system
     *
     * @param sourceSystem the value for pbis_language.source_system
     *
     * @mbg.generated
     */
    public void setSourceSystem(Byte sourceSystem) {
        this.sourceSystem = sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.source_update_time
     *
     * @return the value of pbis_language.source_update_time
     *
     * @mbg.generated
     */
    public Date getSourceUpdateTime() {
        return sourceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.source_update_time
     *
     * @param sourceUpdateTime the value for pbis_language.source_update_time
     *
     * @mbg.generated
     */
    public void setSourceUpdateTime(Date sourceUpdateTime) {
        this.sourceUpdateTime = sourceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.insert_time
     *
     * @return the value of pbis_language.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.insert_time
     *
     * @param insertTime the value for pbis_language.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.last_update_time
     *
     * @return the value of pbis_language.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.last_update_time
     *
     * @param lastUpdateTime the value for pbis_language.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_language.is_del
     *
     * @return the value of pbis_language.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_language.is_del
     *
     * @param isDel the value for pbis_language.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}