package ds.zjc.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pbis_site
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Site implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   站点类型:1=主站点,2=子站点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.site_type
     *
     * @mbg.generated
     */
    private Byte siteType;

    /**
     * Database Column Remarks:
     *   主站点类型:1=自营站点；2=第三方站点【SHEIN=1，AMAZON=2】只有主站点才有该信息；子站点不含站点类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.main_site_type
     *
     * @mbg.generated
     */
    private Byte mainSiteType;

    /**
     * Database Column Remarks:
     *   站点名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.site_name
     *
     * @mbg.generated
     */
    private String siteName;

    /**
     * Database Column Remarks:
     *   站点缩写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.site_abbr
     *
     * @mbg.generated
     */
    private String siteAbbr;

    /**
     * Database Column Remarks:
     *   父级站点缩写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.parent_site_abbr
     *
     * @mbg.generated
     */
    private String parentSiteAbbr;

    /**
     * Database Column Remarks:
     *   是否中台使用:1=使用,0=不使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     * Database Column Remarks:
     *   1代表主数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.source_system
     *
     * @mbg.generated
     */
    private Byte sourceSystem;

    /**
     * Database Column Remarks:
     *   来源系统更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.source_update_time
     *
     * @mbg.generated
     */
    private Date sourceUpdateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   记录插入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * Database Column Remarks:
     *   记录更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pbis_site.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pbis_site
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.id
     *
     * @return the value of pbis_site.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.id
     *
     * @param id the value for pbis_site.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.site_type
     *
     * @return the value of pbis_site.site_type
     *
     * @mbg.generated
     */
    public Byte getSiteType() {
        return siteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.site_type
     *
     * @param siteType the value for pbis_site.site_type
     *
     * @mbg.generated
     */
    public void setSiteType(Byte siteType) {
        this.siteType = siteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.main_site_type
     *
     * @return the value of pbis_site.main_site_type
     *
     * @mbg.generated
     */
    public Byte getMainSiteType() {
        return mainSiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.main_site_type
     *
     * @param mainSiteType the value for pbis_site.main_site_type
     *
     * @mbg.generated
     */
    public void setMainSiteType(Byte mainSiteType) {
        this.mainSiteType = mainSiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.site_name
     *
     * @return the value of pbis_site.site_name
     *
     * @mbg.generated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.site_name
     *
     * @param siteName the value for pbis_site.site_name
     *
     * @mbg.generated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.site_abbr
     *
     * @return the value of pbis_site.site_abbr
     *
     * @mbg.generated
     */
    public String getSiteAbbr() {
        return siteAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.site_abbr
     *
     * @param siteAbbr the value for pbis_site.site_abbr
     *
     * @mbg.generated
     */
    public void setSiteAbbr(String siteAbbr) {
        this.siteAbbr = siteAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.parent_site_abbr
     *
     * @return the value of pbis_site.parent_site_abbr
     *
     * @mbg.generated
     */
    public String getParentSiteAbbr() {
        return parentSiteAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.parent_site_abbr
     *
     * @param parentSiteAbbr the value for pbis_site.parent_site_abbr
     *
     * @mbg.generated
     */
    public void setParentSiteAbbr(String parentSiteAbbr) {
        this.parentSiteAbbr = parentSiteAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.is_show
     *
     * @return the value of pbis_site.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.is_show
     *
     * @param isShow the value for pbis_site.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.source_system
     *
     * @return the value of pbis_site.source_system
     *
     * @mbg.generated
     */
    public Byte getSourceSystem() {
        return sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.source_system
     *
     * @param sourceSystem the value for pbis_site.source_system
     *
     * @mbg.generated
     */
    public void setSourceSystem(Byte sourceSystem) {
        this.sourceSystem = sourceSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.source_update_time
     *
     * @return the value of pbis_site.source_update_time
     *
     * @mbg.generated
     */
    public Date getSourceUpdateTime() {
        return sourceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.source_update_time
     *
     * @param sourceUpdateTime the value for pbis_site.source_update_time
     *
     * @mbg.generated
     */
    public void setSourceUpdateTime(Date sourceUpdateTime) {
        this.sourceUpdateTime = sourceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.is_del
     *
     * @return the value of pbis_site.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.is_del
     *
     * @param isDel the value for pbis_site.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.insert_time
     *
     * @return the value of pbis_site.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.insert_time
     *
     * @param insertTime the value for pbis_site.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pbis_site.last_update_time
     *
     * @return the value of pbis_site.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pbis_site.last_update_time
     *
     * @param lastUpdateTime the value for pbis_site.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}